services:
  backstage:
    image: backstage:latest
    ports:
      - "7007:7007"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
